name: minifi_app
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons
  cupertino_icons: ^0.1.3
  # Stacked
  stacked: ^1.7.4
  # third-party services
  stacked_services: ^0.4.4+3
  # navigation
  auto_route: ^0.6.4
  # inversion of control
  get_it: ^4.0.2
  injectable: ^0.4.0+1
  # Flutter Spinkit
  flutter_spinkit: ^4.1.2+1
  # Logger
  logger: ^0.9.1

  # http
  http: ^0.12.2
  # intro slider
  intro_slider: ^2.3.1
  #string validator
  string_validator: ^0.1.4
  # flutter toast
  fluttertoast: ^4.0.1
  # url launcher
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Generators
  build_runner: ^1.10.0
  auto_route_generator: ^0.6.4
  injectable_generator: ^0.4.1

  # flutter launcher icons
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  ios: true
  android: "launcher_icon"
  image_path: "assets/icon/minifi_logo_FULL.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icon/
